import {Type} from "@rcsb/rcsb-api-tools/build/RcsbGraphQL/Types/Borrego/GqlTypes";

const BURIAL_FRACTION: "BURIAL_FRACTION" = "BURIAL_FRACTION";
const BURIED_RESIDUES: "BURIED_RESIDUES" = "BURIED_RESIDUES";
const ExtendedTypes = {
    BurialFraction: BURIAL_FRACTION,
    BuriedResidues: BURIED_RESIDUES
};

type MergedType = typeof Type & typeof ExtendedTypes;
const MergedType: MergedType = {
    ActiveSite: Type.ActiveSite,
    AngleOutlier: Type.AngleOutlier,
    Artifact: Type.Artifact,
    Asa: Type.Asa,
    AsaBound: Type.AsaBound,
    AsaUnbound: Type.AsaUnbound,
    BindingSite: Type.BindingSite,
    BondOutlier: Type.BondOutlier,
    BurialFraction: BURIAL_FRACTION,
    BuriedResidues: BURIED_RESIDUES,
    CMannosylationSite: Type.CMannosylationSite,
    CalciumBindingRegion: Type.CalciumBindingRegion,
    CardModel: Type.CardModel,
    Cath: Type.Cath,
    Chain: Type.Chain,
    CisPeptide: Type.CisPeptide,
    CompositionallyBiasedRegion: Type.CompositionallyBiasedRegion,
    CovalentBond: Type.CovalentBond,
    CovalentModificationOfANucleotideBase: Type.CovalentModificationOfANucleotideBase,
    CovalentModificationOfANucleotidePhosphate: Type.CovalentModificationOfANucleotidePhosphate,
    CovalentModificationOfANucleotideSugar: Type.CovalentModificationOfANucleotideSugar,
    CovalentResidueModification: Type.CovalentResidueModification,
    CrossLink: Type.CrossLink,
    Disorder: Type.Disorder,
    DisorderBinding: Type.DisorderBinding,
    DisulfideBridge: Type.DisulfideBridge,
    DnaBindingRegion: Type.DnaBindingRegion,
    Domain: Type.Domain,
    Ecod: Type.Ecod,
    GlycosylationSite: Type.GlycosylationSite,
    HelixP: Type.HelixP,
    HydrogenBond: Type.HydrogenBond,
    Hydropathy: Type.Hydropathy,
    ImgtAntibodyDescription: Type.ImgtAntibodyDescription,
    ImgtAntibodyDomainName: Type.ImgtAntibodyDomainName,
    ImgtAntibodyGeneAlleleName: Type.ImgtAntibodyGeneAlleleName,
    ImgtAntibodyOrganismName: Type.ImgtAntibodyOrganismName,
    ImgtAntibodyProteinName: Type.ImgtAntibodyProteinName,
    ImgtAntibodyReceptorDescription: Type.ImgtAntibodyReceptorDescription,
    ImgtAntibodyReceptorType: Type.ImgtAntibodyReceptorType,
    InitiatorMethionine: Type.InitiatorMethionine,
    IntramembraneRegion: Type.IntramembraneRegion,
    IonicInteraction: Type.IonicInteraction,
    LipidMoietyBindingRegion: Type.LipidMoietyBindingRegion,
    MembraneSegment: Type.MembraneSegment,
    MetalCoordination: Type.MetalCoordination,
    MetalIonBindingSite: Type.MetalIonBindingSite,
    MismatchedBasePairs: Type.MismatchedBasePairs,
    ModifiedMonomer: Type.ModifiedMonomer,
    ModifiedResidue: Type.ModifiedResidue,
    MogulAngleOutlier: Type.MogulAngleOutlier,
    MogulBondOutlier: Type.MogulBondOutlier,
    MutagenesisSite: Type.MutagenesisSite,
    Mutation: Type.Mutation,
    NGlycosylationSite: Type.NGlycosylationSite,
    NonConsecutiveResidues: Type.NonConsecutiveResidues,
    NonStandardAminoAcid: Type.NonStandardAminoAcid,
    NonTerminalResidue: Type.NonTerminalResidue,
    NucleotidePhosphateBindingRegion: Type.NucleotidePhosphateBindingRegion,
    OGlycosylationSite: Type.OGlycosylationSite,
    Peptide: Type.Peptide,
    Pfam: Type.Pfam,
    Propeptide: Type.Propeptide,
    RamachandranOutlier: Type.RamachandranOutlier,
    RegionOfInterest: Type.RegionOfInterest,
    Repeat: Type.Repeat,
    RotamerOutlier: Type.RotamerOutlier,
    RsccOutlier: Type.RsccOutlier,
    RsrzOutlier: Type.RsrzOutlier,
    SGlycosylationSite: Type.SGlycosylationSite,
    SabdabAntibodyAntigenName: Type.SabdabAntibodyAntigenName,
    SabdabAntibodyHeavyChainSubclass: Type.SabdabAntibodyHeavyChainSubclass,
    SabdabAntibodyLightChainSubclass: Type.SabdabAntibodyLightChainSubclass,
    SabdabAntibodyLightChainType: Type.SabdabAntibodyLightChainType,
    SabdabAntibodyName: Type.SabdabAntibodyName,
    SabdabAntibodyTarget: Type.SabdabAntibodyTarget,
    Scop: Type.Scop,
    Scop_2BSuperfamily: Type.Scop_2BSuperfamily,
    Scop_2Family: Type.Scop_2Family,
    Scop_2Superfamily: Type.Scop_2Superfamily,
    SequenceConflict: Type.SequenceConflict,
    SequenceVariant: Type.SequenceVariant,
    Sheet: Type.Sheet,
    ShortSequenceMotif: Type.ShortSequenceMotif,
    SignalPeptide: Type.SignalPeptide,
    Site: Type.Site,
    SpliceVariant: Type.SpliceVariant,
    StereoOutlier: Type.StereoOutlier,
    TransitPeptide: Type.TransitPeptide,
    TransmembraneRegion: Type.TransmembraneRegion,
    UnassignedSecStruct: Type.UnassignedSecStruct,
    UnobservedAtomXyz: Type.UnobservedAtomXyz,
    UnobservedResidueXyz: Type.UnobservedResidueXyz,
    UnsureResidue: Type.UnsureResidue,
    ZeroOccupancyAtomXyz: Type.ZeroOccupancyAtomXyz,
    ZeroOccupancyResidueXyz: Type.ZeroOccupancyResidueXyz,
    ZincFingerRegion: Type.ZincFingerRegion,
    TopologicalDomain: Type.TopologicalDomain
};

type MergedTypeKeys = keyof typeof MergedType;
type FeatureTypeInterface = {[key in MergedTypeKeys]: Type}
export const FeatureType:FeatureTypeInterface = MergedType as unknown as FeatureTypeInterface;
