schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://seqcoordinates.ihm.k8s.rcsb.org/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
